dist: trusty
sudo: required
language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get -qqy update
  - sudo apt-get install -qy libwxgtk3.0-0
  - sudo apt-get install -qy libwxgtk3.0-dev
script:
  - ./configure --test && make && make test
before_deploy:
  - sudo apt-get install -qy python3 python3-pip
  - python -m pip install packagecore
  - packagecore -o dist/ "${TRAVIS_TAG#v}"
deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_ENCRYPTED_TOKEN}
  file_glob: true
  file:
    - dist/*
  skip_cleanup: true
  on:
    tags: true

