language: cpp
compiler:
  - clang
  - gcc


before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libwxgtk
  - sudo apt-get install -y libwxgtk-dev

script:
  - ./configure --test && make && make test
