dist: trusty
sudo: required
language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get -qqy update
  - sudo apt-get install -qy libwxgtk3.0-0v5
  - sudo apt-get install -qy libwxgtk3.0-dev
script:
  - ./configure --test && make && make test
